# Generated by Django 3.2.6 on 2022-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendYourQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('your_queries', models.CharField(max_length=200)),
            ],
        ),
    ]
